### ISSUE TITLE
xadmin for python 3

### ISSUE THREAD

**Issue by javienco** [sshwsfc/xadmin#105]
Will there be a version of xadmin for python 3?

Thanks

**Comment by xiaohailian** [comment]
I has a question :

ImproperlyConfigured at /
GEOS is required and has not been detected. Are you sure it is installed? See also https://docs.djangoproject.com/en/1.8/ref/contrib/gis/install/geolibs/

How can i solve these ? I use the python 3.4.2 and the django 1.8.4 .should i install something ? I have tried to install geos and gdal,but both of them were failed.

**Comment by projektai** [comment]
Hi xiaohailian,

Please use django 1.7 and check if all dependancies have been installed:
virtualenv-3.4 /apps/$PROJECTNAME/env
source /apps/$PROJECTNAME/env/bin/activate
pip install django git+git://github.com/projektai/django-crispy-forms
django-reversion  xlwt-future xlsxwriter pygeocoder psycopg2 sorl-thumbnail
django-debug-toolbar djangorestframework markdown && pip install git+git://
github.com/projektai/django-xadmin
django-admin startproject source /apps/$PROJECTNAME

Please let me know if that helped.

Regards,
Vytautas

**Comment by xiaohailian** [comment]
I do all of things that you provided for me .But the question still happen.Properly cause by using django1.8.4.I still can't solve it.

**Comment by projektai** [comment]
Hi,
Have you configured postgis? This is postgres gis extention?

Regards,
Vytautas

**Comment by xiaohailian** [comment]
I haven't install postgis,but I have install PostgreSQL .Besides,I run the project in windows.

**Comment by projektai** [comment]
Hi,
I don't use windows, I prefer Centos, Fedora or RHEL. Xadmin requires
postgres with enabled postgis extention.

Regards,
Vytautas

**Comment by xiaohailian** [comment]
Hi projektai:
The problem was solved . Because I was installing the OSGeO4w,maybe some package include in it .So  i make it .

**Comment by madthew** [comment]
Any news about python 3 version?
