### ISSUE TITLE
change color of an entire row depending on a attribute value

### ISSUE THREAD

**Issue by arjunnambiartc** [sshwsfc/xadmin#106]
I have a model in which one of the fields is "Change_status".I want the the color of the row to change depending on the value of status.I know that xadmin uses bootstrap so I tried using the bootstrap classes which I had done with a previous hack of the django admin as follows:

def row_attributes(self, obj):
        class_map = {
            2: 'warning',
            3: 'info',
            4: 'success',
            5: 'error',
            6: 'error',
            7: 'error',
            8: 'error',
            10: 'success',
        }

```
    css_class = class_map.get(obj.Change_status)
    if css_class:
        return {'class': css_class}
```

where Change_status is on of the fields in my model.But this does not work in xadmin.Any suggestions ?

**Comment by madthew** [comment]
I can't do it can someone post mor code? where do you declare XXXClass?
