### ISSUE TITLE
Create custom view

### ISSUE THREAD

**Issue by javienco** [sshwsfc/xadmin#119]
I created a view but the context load properly, not load the menu bar and  name app

class MyView(BaseAdminView):
    base_template = 'xadmin/base_site.html'
    @never_cache
    def get(self, request, _args, *_kwargs):
        context = self.get_context()
        return TemplateResponse(self.request, [
            'xadmin/views/Welcome.html'
        ], self.get_context(), current_app=self.admin_site.name)

xadmin.site.register_view(r'^xadmin/welcome/$',MyView, name='welcome')

Any idea?

**Comment by just10minutes** [comment]
@javienco  Do you still use xadmin on your project?

**Comment by ni8mr** [comment]
@javienco ...I have registered my custom view like this. But how can i generate a menu from this ?
