### ISSUE TITLE
1.8 使用 inlines 显示修改页面的时候 can't set attribute 求帮助

### ISSUE THREAD

**Issue by lvusyy** [sshwsfc/xadmin#312]
没用过github 不知道相关规则,请见谅 ...

出错模块 inlines ,我不知道是我自己的代码有问题,还是程序有未被修复的BUG,请大神们查看下. 谢谢

xadmin 1.8 和Master分支下都这样.

django1.8.13 
crispy-forms 1.4.0
reversion 1.10.1

***************************************************************************************

增加的时候正常,

![2345 20160516180535](https://cloud.githubusercontent.com/assets/2316032/15286904/1108c7de-1b92-11e6-8b73-13fbb56e042a.jpg)

修改的时候就出错

错误信息
********************************************************************************************
`AttributeError at /smarker/orderw/1/update/
can't set attribute
Request Method:	GET
Request URL:	http://127.0.0.1:8000/smarker/orderw/1/update/
Django Version:	1.8.13
Exception Type:	AttributeError
Exception Value:	
can't set attribute
Exception Location:	C:\Python27\lib\site-packages\crispy_forms\utils.py in render_field, line 92
Python Executable:	C:\Python27\python.exe
Python Version:	2.7.11
Python Path:	
['E:/CODE/smarkersystem',
 'C:\\Program Files (x86)\\JetBrains\\PyCharm 2016.1\\helpers\\pydev',
 'C:\\Python27\\lib\\site-packages\\aliyun-1.1.0-py2.7.egg',
 'C:\\Python27\\lib\\site-packages\\python_dateutil-2.5.1-py2.7.egg',
 'c:\\users\\dragon\\python-aliyun\\.eggs\\six-1.10.0-py2.7.egg',
 'C:\\Python27\\lib\\site-packages\\django_photologue-3.5.1-py2.7.egg',
 'C:\\Python27\\lib\\site-packages\\exifread-2.1.2-py2.7.egg',
 'C:\\Python27\\lib\\site-packages\\django_sortedm2m-1.2.2-py2.7.egg',
 'C:\\Python27\\lib\\site-packages\\django_xadmin-0.5.0-py2.7.egg',
 'E:\\CODE\\smarkersystem',
 'C:\\Program Files (x86)\\JetBrains\\PyCharm 2016.1\\helpers\\pydev',
 'C:\\WINDOWS\\SYSTEM32\\python27.zip',
 'C:\\Python27\\DLLs',
 'C:\\Python27\\lib',
 'C:\\Python27\\lib\\plat-win',
 'C:\\Python27\\lib\\lib-tk',
 'C:\\Python27',
 'C:\\Python27\\lib\\site-packages',
 'C:\\Python27\\lib\\site-packages\\IPython\\extensions']
Server time:	星期一, 16 五月 2016 17:53:22 +0800
Error during template rendering

In template C:\Python27\lib\site-packages\django_xadmin-0.5.0-py2.7.egg\xadmin\templates\xadmin\edit_inline\stacked.html, error at line 16
can't set attribute
6	{% block formset_form %}
7	  <div class="panel formset-row row fieldset">
8	    <div class="panel-heading">
9	      {% if formset.formset.can_delete %}
10	        <a class="delete-row pull-right"><i class="fa fa-times"></i></a>
11	      {% endif %}
12	      <b>{{ formset.opts.verbose_name|title }}:</b>&nbsp;{% if fs.instance.pk %}{{ fs.instance }}{% else %}#<span class="formset-num">{{ forloop.counter }}</span>{% endif %}
13	    </div>
14	    <div class="panel-body formset-form">
15	      {#{% crispy fs formset.formset.helper %}#}
16	
            
      {% crispy fs  formset.formset.helper%}
      

      
17	    </div>
18	  </div>
19	{% endblock formset_form %}
20	
21	{% block formset_empty %}
22	  <div class="panel formset-row row fieldset">
23	    <div class="panel-heading">
24	      {% if formset.formset.can_delete %}
25	        <a class="delete-row pull-right"><i class="fa fa-times"></i></a>
26	      {% endif %}`

************************************************************************************
部分我认为相关代码
models

`# 图片/文件 存储

1. class BillImg(models.Model):
2.     hittext = models.CharField(u'描述信息', max_length=50)  # 图片或文件的描述信息
3.     datimes=models.DateTimeField(u'上传图片时间:',auto_now_add=True)
4.     imgsave = models.ImageField(u'存储的路径', upload_to="imageonTheBigBase/%Y/%m/%d") 
5.     in_order = models.ForeignKey(orderw, `verbose_name=u"所属订单",related_name='inorder')

adminx.py
 class BillImgAdmin(object):
    search_fields = ('hittext', 'in_order')
    fields = ('hittext', 'imgsave', 'in_order')
    list_display = search_fields + ('datimes','preview',)
    list_display_links = ('in_order',)
    # list_export = ('xls','json')
    # 只读fields
    # readonly_fields = ('imgsave',)

    ordering = ('-in_order',)
    list_per_page = 10
    def preview(self, obj):
        return '<a href="{0}" target="_blank" data-gallery="gallery"><img src="{0}" height="64" width="64"  class="field_img"  border="5px"></a>' % (obj.imgsave.url)

    preview.short_description = u'图片'
    preview.allow_tags = True`

- class ChoiceImgs(object):
-     model = BillImg
-     extra = 3
-     # style = 'accordion'

**Comment by lvusyy** [comment]
后期测试过程中发现是 adminx.py
这个对象引起的
class BillImgAdmin(object):
因为我 inlines  其他对象的时候都没问题.
inlines 其他对象 有超过两次 ForeignKey 深度之后 
快捷方式添加对象
![1](https://cloud.githubusercontent.com/assets/2316032/15491122/2c495072-21a0-11e6-9038-a61a23b1efa3.png)
ForeignKey下拉框就不会出现
![2](https://cloud.githubusercontent.com/assets/2316032/15491136/482123f6-21a0-11e6-86f7-8a8e7d71ef6f.jpg) 这样.
必须刷新,当然单独添加是没有问题的.

**Comment by lvusyy** [comment]
新版本 已经解决inline 的问题. 但是不能inline 2层.
但是 foreignkey 下拉还是 有的出不来. 搞不懂.

**Comment by VessaliusOz** [comment]
xadmin中inline不能像admin里面那样有额外添加的链接么？
![image](https://user-images.githubusercontent.com/19574792/35793350-43dfb3a8-0a8c-11e8-84b6-433028cb94e5.png)

![image](https://user-images.githubusercontent.com/19574792/35793384-63dbd6fa-0a8c-11e8-906a-48498aec9985.png)

**Comment by VessaliusOz** [comment]
xadmin中inline不能像admin里面那样有额外添加关联对象的链接么？xadmin中虽然设置了max_num,当max_num > extra时，似乎只会显示extra的数量，并不能动态的添加直到到达max_num的数量。
![image](https://user-images.githubusercontent.com/19574792/35793516-e5605a02-0a8c-11e8-9e34-6e5da0fd2627.png)
![image](https://user-images.githubusercontent.com/19574792/35793528-eee50988-0a8c-11e8-8898-3daf4c186fb0.png)
