### ISSUE TITLE
NoReverseMatch during reverse URLs defined in get_urls of custom app's adminx.py

### ISSUE THREAD

**Issue by apprentice1985** [sshwsfc/xadmin#325]
# Question: How to add url in adminx.py of app?
I define one model User in custom app users, so define adminx.py under app users also. Try to add more URL pattern in adminx.py by adding it in function get_urls. But it always report NoReverseMatch,like below. Seems like it is unusable to add more URL in get_urls, but how should be do this?

>NoReverseMatch at /xadmin/users/user/
Reverse for 'user_user_change_secret' with arguments '(3L,)' and keyword arguments '{}' not found. 0 pattern(s) tried: []
Request Method:	GET
Request URL:	http://127.0.0.1:8000/xadmin/users/user/
Django Version:	1.9.2
Exception Type:	NoReverseMatch
Exception Value:	
Reverse for 'user_user_change_secret' with arguments '(3L,)' and keyword arguments '{}' not found. 0 pattern(s) tried: []
Exception Location:	C:\Python27\lib\site-packages\django-1.9.2-py2.7.egg\django\core\urlresolvers.py in _reverse_with_prefix, line 512
Python Executable:	C:\Python27\python.exe
Python Version:	2.7.11

In users/adminx.py,
```
class UserAdmin(object):
    list_display = ('username',...,'change_secret_button')

def get_urls(self):
        name_change_secret = '{0}_{1}_change_secret'.format(self.model._meta.app_label, self.model._meta.model_name)
        name_qrcode_img = '{0}_{1}_get_qrcode_image'.format(self.model._meta.app_label, self.model._meta.model_name)
        patterns = [
            url(r'^(\d+)/change_secret/$',self.admin_site.admin_view(self.change_secret),name=name_change_secret),
            url(r'^get_qrcode_image/$',self.admin_site.admin_view(self.get_qrcode_image),name=name_qrcode_img),
            url(r'^(\d+)/password/$',self.admin_site.admin_view(self.user_change_password)),
        ]
        return patterns
def change_secret_button(self,user):
            return '<a href="{0}">更换密钥</a>'.format(reverse('xadmin:user_user_change_secret',args=[user.id]))
xadmin.site.register(User, UserAdmin)
```

**Comment by alexsilva** [comment]
What are you trying to do is not possible [Sites L306](https://github.com/sshwsfc/xadmin/blob/master/xadmin/sites.py#L306)
There is no view object when the urls are being processed.
Has no way of to call a method get_urls.

**Comment by apprentice1985** [comment]
Thanks for your suggetion, it was helpful. It seems ok now, I did (1)Change function view to ModelAdminView, that's change function change_secret_button to admin view class ChangeSecretView.(2)use register_view to register the URL with ChangeSecretView.

`xadmin.site.register_view(r'^users/user/(\d+)/change_secret/$',ChangeSecretView, name=name_change_secret)
`
