### ISSUE TITLE
修改用户密码表单404

### ISSUE THREAD

**Issue by luckwang** [sshwsfc/xadmin#338]
点击修改用户密码的表单时返回404

**Comment by zaxlct** [comment]
@luckwang 
https://github.com/zaxlct/MxOnline_Django/commit/fa3cb92d2a28d79a8acede41d60abc048e431be6
遇到同样的问题，解决了。
更换一下 url ，`users/userprofile` 是我自己建的用户表替换了 django 自带的 user 表
