### ISSUE TITLE
后台列表中出现多余的 空 列

### ISSUE THREAD

**Issue by uhayate** [sshwsfc/xadmin#356]
不管在自己注册的类里面还是django的auth里面，都会显示一个多余的 空 列。
如下图最右边的列
[](url)
![qq 20161112205142](https://cloud.githubusercontent.com/assets/11769715/20237893/dfc96546-a919-11e6-8f38-07fce5aba538.png)
请问怎么去掉这个。看着很不美观。

**Comment by lvusyy** [comment]
这个你看下 历史 issue. ，好像有个字段，但是我忘记了，如果有时间我又没忘记帮你查下
