### ISSUE TITLE
Inline formsets always rendered after the form

### ISSUE THREAD

**Issue by frmdstryr** [sshwsfc/xadmin#363]
Using a list in:
https://github.com/sshwsfc/xadmin/blob/master/xadmin/plugins/inline.py#L432 

breaks using inlines within a form. They always get rendered at the end. Instead of a list it should use a `collections.OrderedDict` which keeps order AND places them at the right spot within the form.

**Comment by alexsilva** [comment]
I have observed several bugs and applied fixes here [#345](https://github.com/sshwsfc/xadmin/pull/345)
