### ISSUE TITLE
大概什么时候可以兼容django 1.10 +

### ISSUE THREAD

**Issue by XinMa1** [sshwsfc/xadmin#367]
我们项目使用了django 1.10，然后发现需要订制一些admin界面。不知道什么时候，可以兼容1.10。
*******提个建议: 图表统计 确实太少了，需要更为丰富的图表选择(饼图，柱状图......)

**Comment by wgbbiao** [comment]
兼容1.10 了。 请使用源码安装。

**Comment by XinMa1** [comment]
好的
