### ISSUE TITLE
关于用户上传的静态资源一些疑问。

### ISSUE THREAD

**Issue by jacobzheng** [sshwsfc/xadmin#388]
你好，也许这并不是xadmin所要去解决的事情，但是还是有一个疑问，目前静态资源上传通过imageField上传到服务器磁盘，但是目前大环境来讲基本这些图片，视频，音频大文件都会采用云存储，配合cdn网络。很少会有人自己部署静态资源服务器。

我现在有个问题，就是想把静态资源上传到第三方的云存储服务器。有没有什么好的方式？？第一次接触django，使用了xadmin很强大，但是这个问题还是不能解决，可以自定义field吗？？并且xadmin可以重写相应的前端上传接口？？？第一次使用python很多问题不是很清楚的表达，希望能给一些建议。

**Comment by jasonchou3** [comment]
直接去七牛下载他们的包就可以直接把图存到七牛

**Comment by kakaok** [comment]
我也是有这个疑问，如何在xadmin中上传一些资源到指定的文件服务器，是自己架设的文件服务器上 看了下Storage 在django 2.0下没有成功  迁移的时候总是报错  
    "topics/migrations/#migration-serializing" % (value, get_docs_version())
ValueError: Cannot serialize: <products.models.UptoFileSystem object at 0x000000
0004B77470>
There are some values Django cannot serialize into migration files.
 
class UptoFileSystem(Storage):
    # 图片保存路径
    BASE_URL = "***************fileManage/upload/uploadFile.do"
    Full_File_Url = None

    def send_file(self, name, filename, file):
        try:
            path = "/upload/weixin/{0}/".format(filename) + datetime.now().strftime("%Y%m%d")
            # name 原始文件名称  path:文件服务器要存储的相对路径
            payload = {"name": name, "path": path}
            rt = requests.post(url=self.BASE_URL, data=payload, files={
                "field1": ("filename1", file)})
            Full_File_Url = rt.json()["url"]
            return Full_File_Url
        except Exception as error_msg:
            print(error_msg)
            return None

    def open(self, name, mode='rb'):
        """
        Retrieves the specified file from storage.
        """
        return self._open(name, mode)

    def _save(self, name, content):
        try:
            self.send_file(name, name, content)
        except Exception as error_msg:
            print(error_msg)
            return ""

    def exists(self, name):
        return True

    def listdir(self, path):
        pass

    def size(self, name):
        return 0

    def url(self, name):
        if self.Full_File_Url:
            return self.Full_File_Url
        else:
            return ""

    def __str__(self):
        return self.Full_File_Url

class Products(models.Model):
    '''
    企业名称与对应产品信息模型
    '''
    appId = models.CharField(max_length=100, verbose_name='小程序appId', null=True, blank=True, default='')
    appName = models.CharField(max_length=100, verbose_name='小程序名称', null=True, blank=True, default='')
    imgUrl = models.FileField(storage=UptoFileSystem(), verbose_name='产品图片路径', default='')


各位给看下 该如何修改
