### ISSUE TITLE
数据量太大，很慢，很多时候打不开，python 占用内存很高，应该是分页查询sql 时，没有查询出来，如何解决？？？

### ISSUE THREAD

**Issue by liwei01** [sshwsfc/xadmin#432]
import xadmin
from xadmin import views
from models import *

class MyUserAdmin(object):
    verbose_name = '用户'
    list_display = ('name')
    list_per_page = 10
xadmin.site.register(MyUser, MyUserAdmin)

# 这样是显示一个用户表，数据量太大，很慢，很多时候打不开，python 占用内存很高，应该是分页查询sql 时，没有查询出来，如何解决？？？
# 前端用 Django高效率分页方法 如下：
http://blog.csdn.net/zgyulongfei/article/details/8842338
都正常
在这里先谢谢了！！！

**Comment by wgbbiao** [comment]
试试主线吧．我记得改过这个问题了．

**Comment by liwei01** [comment]
我现在用的是 xadmin-django1.11    ，主线支持django 1.11 么

**Comment by finald** [comment]
我也遇到了这种情况，表中有200w的数据，本地调试时候，一进那张表的显示界面就卡住 内存占满，显示不出来

**Comment by liwei01** [comment]
用主线  的  可以打开，100W之前的还好，100W之后的分页就慢慢的了,但可以打开

**Comment by wgbbiao** [comment]
主线支持1.11,请放心使用。
