### ISSUE TITLE
User问题

### ISSUE THREAD

**Issue by fir5** [sshwsfc/xadmin#442]
由于业务需要我们重写了DJango的User，返回的字段为user_uuid。
`def __unicode__(self):
    return self.user_uuid`
在xadmin进行管理的时候，和User有主外键关系的表管理在User字段显示的都是user_uuid，怎么样可以改变便是为User表中的其他字段

**Comment by Dorxa** [comment]
class UserAdmin(admin.ModelAdmin):
    list_display = (..., 'get_author')

    def get_author(self, obj):
        return obj.book.author
    get_author.short_description = 'Author'
    get_author.admin_order_field = 'book__author'
[https://stackoverflow.com/questions/163823/can-list-display-in-a-django-modeladmin-display-attributes-of-foreignkey-field](url)

**Comment by fir5** [comment]
It works
