### ISSUE TITLE
Django 1.11.6 migrate error

### ISSUE THREAD

**Issue by lorenzo33** [sshwsfc/xadmin#454]
Hi,

I must upgrade my django version from 1.9.13 to 1.11.6 for support reasons.
I'm testing with a virtualenv.
I use django==1.11.6, xadmin==0.6.1.

When I run python manage.py migrate command, I've the following error : 
`from django.forms.widgets import RadioFieldRenderer, RadioChoiceInput
ImportError: cannot import name RadioFieldRenderer`

I saw the #387 issue but i didn't understand the issue.

Please help me with the correct code.

Thanks.

**Comment by jenguo** [comment]
Use the latest version of xadmin.

**Comment by lorenzo33** [comment]
Download of last version fixed the error message.

Thanks.
