### ISSUE TITLE
添加自定义的html 嵌入到xadmin框架

### ISSUE THREAD

**Issue by Dorxa** [sshwsfc/xadmin#482]
请问 xadmin整个框架可以添加自己的html页面吗，保留顶栏和左侧栏，在中间区域显示自己的页面

**Comment by wgbbiao** [comment]
可以，自定义页面 看文档吧．https://xadmin.readthedocs.io/en/latest/views_api.html

**Comment by Dorxa** [comment]
谢谢，我也在参考 主页和修改密码页面的设计

**Comment by webjipeng** [comment]
兄弟 这个问题解决了没
