### ISSUE TITLE
django2.0版本的 xadmin 支持面向对象权限的 django-guardian吗？

### ISSUE THREAD

**Issue by hequan2017** [sshwsfc/xadmin#494]
如果支持，有例子吗？

**Comment by hyzx86** [comment]
写代码的不应该穿西装。。感觉像卖房的:smile:

**Comment by alexsilva** [comment]
I'm working on it. It is in the initial phase but it already works [xadmin.plugin.guardian](https://github.com/alexsilva/xadmin.plugin.guardian)
