### ISSUE TITLE
xadmin登录是出现TemplateDoesNotExist

### ISSUE THREAD

**Issue by boomxy** [sshwsfc/xadmin#500]
TemplateDoesNotExist at /xadmin/
xadmin/views/index.html

。。。

Template-loader postmortem

Django tried loading these templates, in this order:

Using engine django:
django.template.loaders.filesystem.Loader: <我的工作路径*-*>\templates\xadmin\views\index.html (Source does not exist)

**Comment by cupen** [comment]
那…… 这个路径存在不？

**Comment by boomxy** [comment]
开始使用自带的admin登录，由于session的缘故不需要登录是可以进入管理页面的。退出后，重新登录，就出现了如上的情况，而且查找了一下...xadmin\views\index.html 发现views下是没有index页面的。

**Comment by cupen** [comment]
什么版本的？ 有重现的例子不？

**Comment by boomxy** [comment]
最新，仓库源码装的，在做项目，几天一直是那样，尝试新创建工程使用，还是一样的结果。
py 2.7.10  django==1.9.8 。  找了一个老的版本可以用了（因为做项目，为了不耽误时间-_-）

**Comment by cupen** [comment]
哦耶，那就完事大吉啦。
p.s. 没用过的版本一概帮不上。
