### ISSUE TITLE
官网demo打不开，文档也访问不了403cuowu

### ISSUE THREAD

**Issue by JayTam** [sshwsfc/xadmin#513]
官网demo报错：
![sd](https://user-images.githubusercontent.com/31993846/35469118-49f09160-0369-11e8-939a-2798532cc385.png)

**Comment by chentao169** [comment]
happened to me too

**Comment by paulzhousz** [comment]
doc can't access for http 403

**Comment by zhangxu3486432** [comment]
今天刚开始使用xadmin，官网就各种403禁止访问，而且额，中文文档竟然看不了？
