### ISSUE TITLE
django2.0分支 xadmin.site.register注册之后，后台看不到

### ISSUE THREAD

**Issue by Zerahhah** [sshwsfc/xadmin#518]
生产模式,DEBUG = False
使用数据库为mysql
python版本为3.5
原admin.py中已经注释掉了
新adminx.py如下：
import xadmin
from .models import Article
class ArticleAdmin(object):
    pass
xadmin.site.register(Article,ArticleAdmin)

setting.py中也注册了xadmin，如下：
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'article',
    'xadmin',
    'crispy_forms',
    'reversion',
]

路径也设置了，在setting.py中。如下：
sys.path.insert(0, os.path.join(BASE_DIR, 'extra_apps'))

在urls.py中，设置了autodiscover，如下：
xadmin.autodiscover()
urlpatterns = [
    path('xadmin/', xadmin.site.urls),
]

已经makemigrations和migrate了
可以进入后台，但是看不到注册的表。
之前的admin是可以看见的。

**Comment by JayTam** [comment]
要在app下创建adminx.py  然后在里面注册模型，具体写法看我github这个项目
https://github.com/JayTam/EduOnline

**Comment by Zerahhah** [comment]
@JayTam 是的呀 是在app下创建的adminx.py
你的项目是django2.0+ 加 xadmin的django2.0分支，后台可以看到注册的model吗

**Comment by Zerahhah** [comment]
测试了一下，在DEBUG=True，也就是开发模式下，在xadmin后台看不到注册的model
在DEBUG=False，也就是生产模式下。我用的nginx + uwsgi + django ，在xadmin后台看不到注册的model

**Comment by JayTam** [comment]
这个我还没试过的，我也仅仅是在开发模式

**Comment by henry-newbie** [comment]
@Zerahhah 请教下，这个问题解决了，我已经找到了好几天，还是没解决，谢谢

**Comment by henry-newbie** [comment]
> @Zerahhah 请教下，这个问题解决了，我已经找到了好几天，还是没解决，谢谢

找到问题了，nav_menu保存在了session中，但是register新的模块之后，session并没有更新，所以禁用session就可以了，注释掉base.py以下代码
if not settings.DEBUG and 'nav_menu' in self.request.session:
        nav_menu = json.loads(self.request.session['nav_menu'])

if not settings.DEBUG:
        self.request.session['nav_menu'] = json.dumps(nav_menu, cls=JSONEncoder, ensure_ascii=False)
        self.request.session.modified = True
