### ISSUE TITLE
django2.0 Xadmin后台管理，图片要重传

### ISSUE THREAD

**Issue by chenjobin** [sshwsfc/xadmin#523]
![](https://github.com/chenjobin/learngit/blob/master/20180223222431.png?raw=true)
如图所示，之前创建的时候已经有logo了，但是，修改这个页面上其他数据的时候，logo也要重传，也就是说它没有默认填入得到原先的图片路径吧。怎么改0 0.求教。
环境如下
certifi                   2018.1.18                py35_0
diff-match-patch          20121119                  <pip>
Django                    2.0.2                     <pip>
django-crispy-forms       1.7.0                     <pip>
django-formtools          2.1                       <pip>
django-import-export      1.0.0                     <pip>
django-pure-pagination    0.3.0                     <pip>
django-ranged-response    0.2.0                     <pip>
django-reversion          2.0.13                    <pip>
django-simple-captcha     0.5.6                     <pip>
et-xmlfile                1.0.1                     <pip>
future                    0.16.0                    <pip>
httplib2                  0.9.2                     <pip>
jdcal                     1.3                       <pip>
mysqlclient               1.3.12                    <pip>
odfpy                     1.3.6                     <pip>
openpyxl                  2.5.0                     <pip>
Pillow                    5.0.0                     <pip>
pip                       9.0.1            py35h691316f_4
python                    3.5.4               h1357f44_23
pytz                      2018.3                    <pip>
PyYAML                    3.12                      <pip>
setuptools                38.5.1                   py35_0
six                       1.11.0                    <pip>
tablib                    0.12.1                    <pip>
unicodecsv                0.14.1                    <pip>
vc                        14                   h0510ff6_3
vs2015_runtime            14.0.25123                    3
wfastcgi                  3.0.0                     <pip>
wheel                     0.30.0           py35h38a90bc_1
wincertstore              0.2              py35hfebbdb8_0
xlrd                      1.1.0                     <pip>
xlwt                      1.3.0                     <pip>

**Comment by JayTam** [comment]
那你因为你图片字段不能为空，重新打开一次，图片地址不会填充上去，设置可以为空就能解决

**Comment by chenjobin** [comment]
@JayTam 谢啦。前几日突然发现是必填字段，弄掉了也就好了
