### ISSUE TITLE
安装django2分支后查询用户信息报错list index out of range

### ISSUE THREAD

**Issue by jiangjun0130** [sshwsfc/xadmin#528]
点击用户信息进行修改或查看详情后，页面报错。
IndexError at /xadmin/users/userprofile/2/update/
list index out of range。

堆栈信息：
{% if field\|is_checkboxselectmultiple %}
{% include 'bootstrap3/layout/checkboxselectmultiple.html' %}
{% endif %}
 
{% if field\|is_radioselect %}
{% include 'bootstrap3/layout/radioselect.html' %}
{% endif %}
 
{% if not field\|is_checkboxselectmultiple and not field\|is_radioselect %}
 {% if field\|is_checkbox and form_show_labels %}
<label for="{{ field.id_for_label }}" class="{% if field.field.required %} requiredField{% endif %}">
{% crispy_field field %}
{{ field.label\|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
</label>
{% include 'bootstrap3/layout/help_text_and_errors.html' %}
{% else %}
<div class="controls {{ field_class }}">
{% crispy_field field %}
{% include 'bootstrap3/layout/help_text_and_errors.html' %}
</div>

**Comment by bambuua** [comment]
你是不添加了DateTimeField？ 如果是的话，你去xadmin下边的widgets.py文件中，找AdminSplitDateTime这个class，里边儿在分割HTML时有问题，导致本来应该是两个的input组合到一起了，后边在取出第二个input的时候就会报这个错误，下边是修改过后的
        input_html = [ht for ht in super(AdminSplitDateTime, self).render(name, value, attrs).split('>') if ht != '']
        # return input_html
        return mark_safe('<div class="datetime clearfix"><div class="input-group date bootstrap-datepicker"><span class="input-group-addon"><i class="fa fa-calendar"></i></span>%s'
                         '<span class="input-group-btn"><button class="btn btn-default" type="button">%s</button></span></div>'
                         '<div class="input-group time bootstrap-clockpicker"><span class="input-group-addon"><i class="fa fa-clock-o">'
                         '</i></span>%s<span class="input-group-btn"><button class="btn btn-default" type="button">%s</button></span></div></div>' % (input_html[0]+'>', _(u'Today'), input_html[1]+'>', _(u'Now')))

**Comment by jiangjun0130** [comment]
问题解决了，谢谢！！！
