### ISSUE TITLE
django2分支，后台添加修改页面 list index out of range

### ISSUE THREAD

**Issue by webjipeng** [sshwsfc/xadmin#535]
list index out of range

{% if field\|is_checkboxselectmultiple %}
{% include 'bootstrap3/layout/checkboxselectmultiple.html' %}
{% endif %}
 
{% if field\|is_radioselect %}
{% include 'bootstrap3/layout/radioselect.html' %}
{% endif %}
 
{% if not field\|is_checkboxselectmultiple and not field\|is_radioselect %}
{% if field\|is_checkbox and form_show_labels %}
<label for="{{ field.id_for_label }}" class="{% if field.field.required %} requiredField{% endif %}">
{% crispy_field field %}
{{ field.label\|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
</label>
{% include 'bootstrap3/layout/help_text_and_errors.html' %}
{% else %}
<div class="controls {{ field_class }}">
{% crispy_field field %}
{% include 'bootstrap3/layout/help_text_and_errors.html' %}
</div>

**Comment by nikolas310** [comment]
Problem is in widgets.py 77 number line
`return mark_safe('<div class="datetime clearfix"><div class="input-group date bootstrap-datepicker"><span class="input-group-addon"><i class="fa fa-calendar"></i></span>%s'
                         '<span class="input-group-btn"><button class="btn btn-default" type="button">%s</button></span></div>'
                         '<div class="input-group time bootstrap-clockpicker"><span class="input-group-addon"><i class="fa fa-clock-o">'
                         '</i></span>%s<span class="input-group-btn"><button class="btn btn-default" type="button">%s</button></span></div></div>' % (**input_html[0]**, _(u'Today'), **input_html[1]**, _(u'Now')))
`

**Comment by russell310** [comment]
Change widget 75 number line
replace
`input_html = [ht for ht in super(AdminSplitDateTime, self).render(name, value, attrs).split('\n') if ht != '']`
with
`input_html = [ht for ht in super(AdminSplitDateTime, self).render(name, value, attrs).split('>') if ht != '']`
