### ISSUE TITLE
在xadmin自己的某个model的某个字段中输入然后保存很长的文本出错

### ISSUE THREAD

**Issue by nagaame** [sshwsfc/xadmin#567]
字段是Textfiled类型, 数据库使用的是postgresql, xadmin版本2.0.1
错误是:

- DataError at /xadmin/api/notesinfo/171/update/
- value too long for type character varying(200)
- Request Method:	POST
- Request URL:	http://127.0.0.1:9000/xadmin/api/notesinfo/171/update/
- Django Version:	2.0.2
- Exception Type:	DataError
- Exception Value: value too long for type character varying(200)

自带的admin保存不会出现这个问题

**Comment by zhangneng888** [comment]
那你就改成300
