### ISSUE TITLE
请问一下，有没有办法限制外键在后台的显示内容呢？

### ISSUE THREAD

**Issue by miaogen123** [sshwsfc/xadmin#600]
我想根据用户的权限来管理外键的显示，如果是admin就显示外键的所有内容，如果不是admin，就默认的使用request.user作为外键指向的内容，但查了资料以后，发现都是针对原始的django自带的admin的操作，不知道在xadmin下如何实现？

**Comment by Ice-Panda** [comment]
老哥，后来找到方法了吗？我也碰到个同样的需求

**Comment by miaogen123** [comment]
老实讲，忘了~~~
