### ISSUE TITLE
in Django2：TypeError: render() got an unexpected keyword argument 'renderer'

### ISSUE THREAD

**Issue by xyliurui** [sshwsfc/xadmin#610]
这个问题都出现在有Image字段的models中，编辑或新增的时候出现

从Django2.1降到Django2.0.8就没问题了

**Comment by vip68** [comment]
试试看
https://github.com/vip68/xadmin_bugfix.git

**Comment by xyliurui** [comment]
可以描述下怎么修复吗，谢谢

**Comment by zegzhi** [comment]
@xyliurui  https://github.com/vip68/xadmin_bugfix/commit/344487d80e6ff830f39b3526ee024231921c074d

**Comment by wgbbiao** [comment]
有朋友提交修改方法了。已经合并到 分支 django2。

**Comment by xianfuxing** [comment]
django 更新太快了，适配问题一个接一个。。
