### ISSUE TITLE
Django 2.1 中后台中删除数据抛出异常

### ISSUE THREAD

**Issue by zmaxple** [sshwsfc/xadmin#612]
django/contrib/admin/utils.py 

112 行附近
```
def get_deleted_objects(objs, opts, user, admin_site, using):
    ...
```
在 Django 2.1 中变更为：
```
def get_deleted_objects(objs, request, admin_site):
    ...
```
而 Django 项目中并没有适配 这个变化,在 `xadmin/xadmin/plugins/actions.py` 中94行仍然使用旧的代码
```
deletable_objects, model_count, perms_needed, protected = get_deleted_objects(
            queryset, self.opts, self.user, self.admin_site, using)
```

https://docs.djangoproject.com/zh-hans/2.1/ref/contrib/admin/#django.contrib.admin.ModelAdmin.get_deleted_objects

希望能尽快适配这一个变化，感谢你们为开源社区作出的贡献与努力。 
@wgbbiao

**Comment by whnet** [comment]
这个问题怎么修改的，xiongdei

**Comment by zmaxple** [comment]
@whnet 
xadmin 中仍然使用 Django 2.0 的代码，所以目前只能把 Django 版本退回到 2.0

```
pip uninstall django
pip install django==2.0
```

**Comment by Fabriceli** [comment]
估计xadmin要挂，没人维护了。。。

**Comment by whnet** [comment]
@zmaxple 是的 现在我也使用2.0了
