### ISSUE TITLE
xadmin在django2.1版本是删除表记录失败

### ISSUE THREAD

**Issue by fengxl0** [sshwsfc/xadmin#616]
xadmin在django2.1版本是删除表记录失败，原因是xadmin中的delete.py中导入的django2.1版本的中函数get_deleted_objects现在只接受3个参数，原来是5个参数

**Comment by fengxl0** [comment]
已参照action修改
if django_version > (2, 0):
            setattr(self.admin_site._registry[self.model], 'has_delete_permission', self.has_delete_permission)

(self.deleted_objects, model_count, self.perms_needed, self.protected) = get_deleted_objects([self.obj],  self.request, self.admin_site)

**Comment by wgbbiao** [comment]
重新安装 django2分支，有人提交了image字段类型的pr.

**Comment by fengxl0** [comment]
你说的这个问题，和我说的不是一回事吧？我说的是删表记录失败，是参数个数与django2.1版本不兼容，django2分支，我就是今天又重新安装在基础上改的

**Comment by fengxl0** [comment]
大佬，我说的是针对表数据删除失败，是因为django2.1的参数变化，导致的xadmin中views中的delete的函数get_deleted_objects的参数不一致，和你说的没有啥关系吧

**Comment by fengxl0** [comment]
#612  这为兄弟调用的删除操作和我的不一样，删除的操作不是还有调用的views中delete.py吗？

**Comment by liwei03** [comment]
你解决了这个问题吗?我也遇到了一样的问题请教一下如何解决
