### ISSUE TITLE
【请教】关于xadmin和django-xadmin的区别

### ISSUE THREAD

**Issue by shandyli** [sshwsfc/xadmin#624]
各位好，

环境：
操作系统：CentOS7.1
python：2.7.5
django：1.11.15

问一下，关于xadmin和django-xadmin有啥区别
用pip install xadmin安装的xadmin是0.6.1版
而用pip install django-xadmin安装的django-xadmin是0.5.0版
这两个有啥区别？是需要删除一个版本吗？

谢谢！

**Comment by wgbbiao** [comment]
django-xadmin 改名为xadmin了．
